### ISSUE TITLE
00-test-repo-demo test issue

### ISSUE THREAD

**Issue by clair3st** [codefellows/seattle-301d7#3]
### What is the expected result?
_What are you trying to accomplish?_  
Testing issues workflow.

### What is the actual result? 
_What are you seeing, or what is happening?_  
I clicked the issues button at the top of the lab instructions and it opened this template.

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._
No error message

### What steps have you taken to address the problem? 

1. First I re-read the instructions
1. Then I re-drafted my response

## Please place an 'x' inside each set of square brackets before clicking "Submit new issue":
- [x] I have entered the filename and the high-level problem as the title of this issue.
- [x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x] I have not been able to work through the issue after 15 minutes.

**Comment by patci** [comment]
All sections filled out completely and accurately, excellent! 😎
