### ISSUE TITLE
Issue for pre-work assignment for 301d7 on repo 00-test-repo-demo

### ISSUE THREAD

**Issue by meganreardon** [codefellows/seattle-301d7#4]
### What is the expected result?
_What are you trying to accomplish?_  
I am trying to finish the pre-work for the Code Fellows course 301d7 which includes forking, breaking and putting in a pull request for the test demo repo at: https://github.com/codefellows-seattle-301d7/00-test-repo-demo

### What is the actual result? 
_What are you seeing, or what is happening?_  
I am confused by the instructions starting after step #19. I was looking for the Issues Icon somewhere on the Pull Request page for the pull request I sent as part of this assignment.

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._
I saw no error message, but it could be argued that there is an error message flashing in my brain.

### What steps have you taken to address the problem? 

1. First I actually found the Issues Icon on the page of the README file.
1. Then I filled it out and here I am.

## Please place an 'x' inside each set of square brackets before clicking "Submit new issue":
- [x] I have entered the filename and the high-level problem as the title of this issue.
- [x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x] I have not been able to work through the issue after 15 minutes.

**Comment by patci** [comment]
Thank you for solving the tricky issues part! I clarified the instructions, great job! 👍
